# Generated by Django 5.0.4 on 2024-04-26 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quay_type", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("length_m", models.FloatField()),
                ("draft_m", models.FloatField()),
                ("tools", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ship_type", models.CharField(max_length=50)),
                ("size", models.IntegerField()),
                ("length_m", models.FloatField()),
                ("draft_m", models.FloatField()),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                ("required_tools", models.JSONField()),
                (
                    "assigned_quay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ship_quay_api.quay",
                    ),
                ),
            ],
        ),
    ]
